### ISSUE TITLE
[BUG] %playerhead% doesn't render the outer layer of my skin

### ISSUE THREAD

**Issue by ilia-21** [hypherionmc/simple-rpc-public#69]
**Describe the bug**
The outer layer of my minecraft skin (head) is not displayed in discord

**To Reproduce**
1. Set %playerhead% as any image
2. Check your discord activity 

**Expected behavior**
Activity shows both skin layers

**Screenshots**
Discord
![image](https://github.com/hypherionmc/simple-rpc-public/assets/67857080/74d82d61-164a-4eea-a244-47e3bac5d82b)
MultiMC for an example of proper rendering (Expected behavior)
![image](https://github.com/hypherionmc/simple-rpc-public/assets/67857080/b6cbdbaf-0923-42e2-9f28-fa036331e1be)

**Versions (DO NOT USE LATEST! BE SPECIFIC!):**
 - OS: Windows 11 22H2
 - JAVA Version: OpenJDK 17.0.7 2023-04-18 LTS
 - Mod Version: 3.2.3
 - Discord Version: Stable 217126 
 - Minecraft Version: 1.19.4
 - Forge/Fabric Version: 0.14.21

**Comment by hypherionmc** [comment]
That would be an issue with `https://crafatar.com/`. That's the service we use to display the player heads, so it's a bug on their side

**Comment by ilia-21** [comment]
I was able to get crafatar to work so that it displays the outer layer of the skin by adding `?overlay` to the link
`https://crafatar.com/avatars/2d8ae7fe972b432f8fba7315dc522fb4`:
![without overlay](https://crafatar.com/avatars/2d8ae7fe972b432f8fba7315dc522fb4)
`https://crafatar.com/avatars/2d8ae7fe972b432f8fba7315dc522fb4?overlay`:
![with overlay](https://crafatar.com/avatars/2d8ae7fe972b432f8fba7315dc522fb4?overlay)

**Comment by hypherionmc** [comment]
Ah. Didn't know they had a separate thing for that. Will add it in the next update

**Comment by 0xallie** [comment]
Same issue here, for me it just shows all black without `?overlay`. When can we expect the next update?

**Comment by hypherionmc** [comment]
You should be able to use %playerhead%?overlay in the config as a work around for now.

I am a bit swamped with stuff to do, and I'm sick, so I don't get around to modding. So that should be able to get you through until a proper update is made

**Comment by 0xallie** [comment]
Oh duh, how did it not occur to me that I could just do that, I already knew I can use an arbitrary link but I didn't put two and two together.

**Comment by 0xallie** [comment]
Actually, that doesn't seem to work. It results in this:
```
https://media.discordapp.net/external/npK2V3cGOmR2A-y-f5jKCPixBXNJw58Bq7DhffU0zBc/%3Fsize%3D512%3Foverlay/https/crafatar.com/avatars/d7f09baca36646d1a5587fe32c477565
```
I guess I'll just hardcode `https://crafatar.com/avatars/d7f09baca36646d1a5587fe32c477565?overlay` for now, it's not like I plan to use multiple accounts.

**Comment by hypherionmc** [comment]
The issue has been patched internally and will be released along with the 1.20.2 port

**Comment by hypherionmc** [comment]
Issue fixed in 3.2.4

**Comment by 0xallie** [comment]
This is still broken for me somehow, however `%playerhead%?overlay` now works.
